Repository ninetwenty-one/rotten-reviews, pull requests merged in 2018-10, with the labels that each got.

#25 Merge new Travis CI configuration
  .travis.yml
Labels: help wanted

#53 Add basic search in
  bin/rotten-reviews.js
  index.js
  package.json
Labels: enhancement

#61 update tests to work using jest
  index.test.js
  package-lock.json
  package.json
  test/rotten-reviews.spec.js
Labels: help wanted

#12 Merging develop to master for v1.1.0
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  .travis.yml
  README.md
  bin/rotten-reviews.js
  examples/README.md
  examples/get-movie-reviews.js
  examples/get-tv-show-reviews.js
  features/rotten-movie-reviews.feature
  features/support/steps.js
  features/support/world.js
  index.js
  index.test.js
  package-lock.json
  package.json
  test/rotten-reviews.spec.js
Labels: hacktoberfest, help wanted, question
